export type Lang = "en" | "mr";

export const t = (en: string, mr: string, lang: Lang) => lang === "en" ? en : mr;

export const programs = [
  {
    id: "pilates-group",
    icon: "🧘",
    category: "pilates",
    title_en: "Group Pilates",
    title_mr: "ग्रुप पिलाटेस",
    desc_en: "Live Zoom sessions with a certified Pilates coach. Small batches for personalized attention.",
    desc_mr: "प्रमाणित पिलाटेस कोचसह थेट झूम सेशन्स. वैयक्तिक लक्षासाठी छोटे बॅच.",
    price: 2999,
    duration_en: "8 weeks · 3x/week",
    duration_mr: "८ आठवडे · ३ वेळा/आठवडा",
    level_en: "Beginner to Intermediate",
    level_mr: "नवशिके ते मध्यम",
    badge_en: "Most Popular",
    badge_mr: "सर्वात लोकप्रिय",
    image: "https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "pilates-individual",
    icon: "🤸",
    category: "pilates",
    title_en: "Individual Pilates",
    title_mr: "वैयक्तिक पिलाटेस",
    desc_en: "One-on-one sessions tailored to your body and goals. Maximum personalisation.",
    desc_mr: "तुमच्या शरीर आणि उद्दिष्टांनुसार तयार केलेले एक-एक सेशन्स.",
    price: 5999,
    duration_en: "Per session · 60 min",
    duration_mr: "प्रति सेशन · ६० मिनिटे",
    level_en: "All levels",
    level_mr: "सर्व स्तर",
    badge_en: "",
    badge_mr: "",
    image: "https://images.unsplash.com/photo-1679688301686-b164852aed9b?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "strength",
    icon: "💪",
    category: "strength",
    title_en: "Strength & Muscle",
    title_mr: "ताकद आणि स्नायू",
    desc_en: "Progressive strength training designed for adults 40+. Build muscle, improve bone density.",
    desc_mr: "४०+ वयोगटासाठी प्रगतीशील शक्ती प्रशिक्षण. स्नायू बांधा, हाडांची घनता सुधारा.",
    price: 3499,
    duration_en: "12 weeks · 3x/week",
    duration_mr: "१२ आठवडे · ३ वेळा/आठवडा",
    level_en: "Beginner",
    level_mr: "नवशिके",
    badge_en: "New",
    badge_mr: "नवीन",
    image: "https://images.unsplash.com/photo-1692372372810-c848c9cca1c5?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "nutrition",
    icon: "🥗",
    category: "nutrition",
    title_en: "Nutrition Program",
    title_mr: "पोषण कार्यक्रम",
    desc_en: "Personalised nutrition plans by a certified nutritionist. Food as medicine for 40+.",
    desc_mr: "प्रमाणित पोषणतज्ञाद्वारे वैयक्तिकृत पोषण योजना. ४०+ साठी औषध म्हणून अन्न.",
    price: 2499,
    duration_en: "8 weeks · Weekly check-in",
    duration_mr: "८ आठवडे · साप्ताहिक तपासणी",
    level_en: "All levels",
    level_mr: "सर्व स्तर",
    badge_en: "",
    badge_mr: "",
    image: "https://images.unsplash.com/photo-1621886178958-be42369fc9e7?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "physio",
    icon: "🦴",
    category: "physio",
    title_en: "Physiotherapy",
    title_mr: "फिजिओथेरपी",
    desc_en: "Doctor-supervised physiotherapy for pain relief, recovery and improved movement.",
    desc_mr: "वेदना आराम, पुनर्प्राप्ती आणि सुधारित हालचालींसाठी डॉक्टर-देखरेख फिजिओथेरपी.",
    price: 1999,
    duration_en: "Per session · 45 min",
    duration_mr: "प्रति सेशन · ४५ मिनिटे",
    level_en: "As prescribed",
    level_mr: "सूचनेनुसार",
    badge_en: "",
    badge_mr: "",
    image: "https://images.unsplash.com/photo-1658314755561-389d5660ee54?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "doctor",
    icon: "🩺",
    category: "medical",
    title_en: "Doctor Consultation",
    title_mr: "डॉक्टर सल्लामसलत",
    desc_en: "Comprehensive internal medicine consultation focused on healthy ageing and longevity.",
    desc_mr: "निरोगी वृद्धत्व आणि दीर्घायुष्यावर केंद्रित सर्वसमावेशक अंतर्गत औषध सल्लामसलत.",
    price: 999,
    duration_en: "30 min online",
    duration_mr: "३० मिनिटे ऑनलाइन",
    level_en: "All",
    level_mr: "सर्व",
    badge_en: "Doctor Led",
    badge_mr: "डॉक्टर नेतृत्व",
    image: "https://images.unsplash.com/photo-1658314755811-73c806249f31?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "hormonal",
    icon: "⚡",
    category: "wellness",
    title_en: "Hormonal Wellness",
    title_mr: "हार्मोनल वेलनेस",
    desc_en: "Evidence-based hormonal health assessment and management for men and women over 40.",
    desc_mr: "४०+ पुरुष आणि महिलांसाठी पुरावा-आधारित हार्मोनल आरोग्य मूल्यांकन.",
    price: 1499,
    duration_en: "Initial + follow-ups",
    duration_mr: "प्रारंभिक + पाठपुरावा",
    level_en: "All",
    level_mr: "सर्व",
    badge_en: "",
    badge_mr: "",
    image: "https://images.unsplash.com/photo-1574310094148-ca48ab86734c?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "recorded",
    icon: "📹",
    category: "pilates",
    title_en: "Recorded Programs",
    title_mr: "रेकॉर्डेड प्रोग्राम्स",
    desc_en: "On-demand Pilates and physiotherapy video library. Practice at your own pace, anytime.",
    desc_mr: "ऑन-डिमांड पिलाटेस आणि फिजिओथेरपी व्हिडिओ लायब्ररी. कधीही सराव करा.",
    price: 1499,
    duration_en: "Lifetime access",
    duration_mr: "आजीवन प्रवेश",
    level_en: "All levels",
    level_mr: "सर्व स्तर",
    badge_en: "",
    badge_mr: "",
    image: "https://images.unsplash.com/photo-1763403921315-f2ef8697199f?w=600&h=400&fit=crop&auto=format",
  },
];

export const professionals = [
  {
    id: "dr-sharma",
    role_en: "Founder & Chief Doctor",
    role_mr: "संस्थापक आणि मुख्य डॉक्टर",
    name_en: "Dr. Rahul Sharma",
    name_mr: "डॉ. राहुल शर्मा",
    qual_en: "MD (Internal Medicine) · 18 years experience",
    qual_mr: "एमडी (अंतर्गत औषध) · १८ वर्षांचा अनुभव",
    spec_en: ["Healthy Ageing", "Hormonal Wellness", "Longevity Medicine"],
    spec_mr: ["निरोगी वृद्धत्व", "हार्मोनल वेलनेस", "दीर्घायुष्य चिकित्सा"],
    bio_en: "Dr. Sharma believes the 40s are the most important decade to invest in your health. Combining evidence-based medicine with a deep understanding of lifestyle, he leads every program at VitalAfter40.",
    bio_mr: "डॉ. शर्मा यांचा विश्वास आहे की ४० चे दशक आरोग्यात गुंतवणूक करण्यासाठी सर्वात महत्त्वाचे दशक आहे.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&auto=format",
    isFounder: true,
  },
  {
    id: "priya-pilates",
    role_en: "Senior Pilates Coach",
    role_mr: "वरिष्ठ पिलाटेस कोच",
    name_en: "Priya Nair",
    name_mr: "प्रिया नायर",
    qual_en: "PMA Certified · 10 years · Rehab Pilates",
    qual_mr: "PMA प्रमाणित · १० वर्षे · पुनर्वसन पिलाटेस",
    spec_en: ["Reformer Pilates", "Post-injury rehab", "Pre & post natal"],
    spec_mr: ["रिफॉर्मर पिलाटेस", "दुखापतीनंतर पुनर्वसन"],
    bio_en: "Priya specialises in therapeutic Pilates for adults managing joint pain, postural issues, and post-injury recovery.",
    bio_mr: "प्रिया सांधेदुखी, पवित्रा समस्या आणि दुखापतीनंतर पुनर्प्राप्तीसाठी उपचारात्मक पिलाटेसमध्ये तज्ञ आहे.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&auto=format",
    isFounder: false,
  },
  {
    id: "amit-physio",
    role_en: "Physiotherapist",
    role_mr: "फिजिओथेरपिस्ट",
    name_en: "Amit Kulkarni",
    name_mr: "अमित कुलकर्णी",
    qual_en: "BPTh, MPTh (Ortho) · 8 years",
    qual_mr: "BPTh, MPTh (Ortho) · ८ वर्षे",
    spec_en: ["Orthopedic rehab", "Sports injury", "Back & neck pain"],
    spec_mr: ["ऑर्थोपेडिक पुनर्वसन", "पाठ आणि मान दुखणे"],
    bio_en: "Amit brings a science-first approach to physiotherapy, with special expertise in musculoskeletal conditions common in adults after 40.",
    bio_mr: "अमित फिजिओथेरपीमध्ये विज्ञान-प्रथम दृष्टीकोन आणतो.",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&auto=format",
    isFounder: false,
  },
  {
    id: "sneha-nutrition",
    role_en: "Nutritionist",
    role_mr: "पोषणतज्ञ",
    name_en: "Sneha Deshpande",
    name_mr: "स्नेहा देशपांडे",
    qual_en: "MSc Nutrition · RD · 7 years",
    qual_mr: "MSc पोषण · RD · ७ वर्षे",
    spec_en: ["Metabolic health", "Weight management", "Gut health"],
    spec_mr: ["चयापचय आरोग्य", "वजन व्यवस्थापन", "आतडे आरोग्य"],
    bio_en: "Sneha takes a food-as-medicine approach to nutrition, creating sustainable eating plans that work with real Indian food.",
    bio_mr: "स्नेहा पोषणासाठी अन्न-औषध दृष्टीकोन घेते.",
    image: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&h=400&fit=crop&auto=format",
    isFounder: false,
  },
];

export const testimonials = [
  {
    name_en: "Meera Joshi",
    name_mr: "मीरा जोशी",
    age: 52,
    city_en: "Pune",
    city_mr: "पुणे",
    program_en: "Group Pilates + Nutrition",
    program_mr: "ग्रुप पिलाटेस + पोषण",
    quote_en: "After just 8 weeks, my back pain is gone and I feel stronger than I did at 35. The assessment really helped me understand where to start.",
    quote_mr: "फक्त ८ आठवड्यांनंतर, माझी पाठदुखी गेली आणि मला ३५ व्या वर्षापेक्षा अधिक मजबूत वाटते.",
    rating: 5,
  },
  {
    name_en: "Suresh Patil",
    name_mr: "सुरेश पाटील",
    age: 47,
    city_en: "Mumbai",
    city_mr: "मुंबई",
    program_en: "Strength + Doctor Consultation",
    program_mr: "ताकद + डॉक्टर सल्लामसलत",
    quote_en: "Dr. Sharma's approach is completely different from any doctor I've met. He actually listens and creates a plan around your life.",
    quote_mr: "डॉ. शर्मा यांचा दृष्टीकोन मी भेटलेल्या कोणत्याही डॉक्टरपेक्षा पूर्णपणे वेगळा आहे.",
    rating: 5,
  },
  {
    name_en: "Anita Kulkarni",
    name_mr: "अनिता कुलकर्णी",
    age: 56,
    city_en: "Nashik",
    city_mr: "नाशिक",
    program_en: "Individual Pilates",
    program_mr: "वैयक्तिक पिलाटेस",
    quote_en: "I was skeptical about online classes but Priya makes every session feel personal. My posture and energy levels have transformed.",
    quote_mr: "मला ऑनलाइन वर्गांबद्दल शंका होती पण प्रिया प्रत्येक सेशन वैयक्तिक वाटवते.",
    rating: 5,
  },
];

export const assessmentQuestions = [
  // Section 1: About You
  { id: "name", section: 1, section_en: "About You", section_mr: "तुमच्याबद्दल", type: "text", q_en: "What's your name?", q_mr: "तुमचे नाव काय आहे?", placeholder_en: "Enter your name", placeholder_mr: "तुमचे नाव प्रविष्ट करा", required: true },
  { id: "phone", section: 1, section_en: "About You", section_mr: "तुमच्याबद्दल", type: "text", q_en: "Your phone number", q_mr: "तुमचा फोन नंबर", placeholder_en: "+91 99999 99999", placeholder_mr: "+91 99999 99999", required: true },
  { id: "age", section: 1, section_en: "About You", section_mr: "तुमच्याबद्दल", type: "number", q_en: "How old are you?", q_mr: "तुमचे वय किती आहे?", placeholder_en: "e.g. 45", placeholder_mr: "उदा. ४५", required: true },
  { id: "gender", section: 1, section_en: "About You", section_mr: "तुमच्याबद्दल", type: "choice", q_en: "What is your gender?", q_mr: "तुमचे लिंग काय आहे?", options: [{ id: "male", label_en: "Male", label_mr: "पुरुष", icon: "👨" }, { id: "female", label_en: "Female", label_mr: "महिला", icon: "👩" }, { id: "other", label_en: "Prefer not to say", label_mr: "सांगण्यास प्राधान्य देत नाही", icon: "🙂" }], required: true },
  { id: "activity", section: 1, section_en: "About You", section_mr: "तुमच्याबद्दल", type: "choice", q_en: "How active are you currently?", q_mr: "तुम्ही सध्या किती सक्रिय आहात?", options: [{ id: "sedentary", label_en: "Mostly sitting", label_mr: "बहुतेक बसणे", icon: "🪑" }, { id: "light", label_en: "Lightly active", label_mr: "हलके सक्रिय", icon: "🚶" }, { id: "moderate", label_en: "Moderately active", label_mr: "मध्यम सक्रिय", icon: "🏃" }, { id: "active", label_en: "Very active", label_mr: "खूप सक्रिय", icon: "🏋️" }], required: true },
  // Section 2: Goals
  { id: "goals", section: 2, section_en: "Your Goals", section_mr: "तुमची उद्दिष्टे", type: "multiselect", q_en: "What would you most like to improve? (Select all that apply)", q_mr: "तुम्हाला सर्वात जास्त काय सुधारायचे आहे?", options: [{ id: "weight", label_en: "Lose weight", label_mr: "वजन कमी करा", icon: "⚖️" }, { id: "muscle", label_en: "Build muscle & strength", label_mr: "स्नायू आणि ताकद वाढवा", icon: "💪" }, { id: "flexibility", label_en: "Improve flexibility", label_mr: "लवचिकता सुधारा", icon: "🤸" }, { id: "posture", label_en: "Improve posture", label_mr: "पवित्रा सुधारा", icon: "🧍" }, { id: "energy", label_en: "Improve energy", label_mr: "ऊर्जा सुधारा", icon: "⚡" }, { id: "sleep", label_en: "Sleep better", label_mr: "चांगले झोपा", icon: "😴" }, { id: "nutrition", label_en: "Improve nutrition", label_mr: "पोषण सुधारा", icon: "🥗" }, { id: "hormonal", label_en: "Hormonal wellness", label_mr: "हार्मोनल वेलनेस", icon: "🔬" }, { id: "pain", label_en: "Reduce pain", label_mr: "वेदना कमी करा", icon: "🩹" }, { id: "fit40", label_en: "Stay fit after 40", label_mr: "४० नंतर तंदुरुस्त राहा", icon: "🎯" }], required: true },
  // Section 3: Movement
  { id: "pain_yn", section: 3, section_en: "Movement", section_mr: "हालचाल", type: "choice", q_en: "Do you experience any pain or physical discomfort?", q_mr: "तुम्हाला कोणतीही वेदना किंवा शारीरिक अस्वस्थता येते का?", options: [{ id: "yes", label_en: "Yes", label_mr: "होय", icon: "⚠️" }, { id: "no", label_en: "No", label_mr: "नाही", icon: "✅" }], required: true },
  { id: "pain_location", section: 3, section_en: "Movement", section_mr: "हालचाल", type: "multiselect", q_en: "Where do you experience pain? (Select all that apply)", q_mr: "तुम्हाला कुठे वेदना होते?", condition: { id: "pain_yn", value: "yes" }, options: [{ id: "back", label_en: "Back", label_mr: "पाठ", icon: "🔙" }, { id: "knee", label_en: "Knees", label_mr: "गुडघे", icon: "🦵" }, { id: "shoulder", label_en: "Shoulders", label_mr: "खांदे", icon: "💆" }, { id: "hip", label_en: "Hips", label_mr: "नितंब", icon: "🦴" }, { id: "neck", label_en: "Neck", label_mr: "मान", icon: "🧠" }], required: false },
  // Section 4: Pilates
  { id: "pilates_exp", section: 4, section_en: "Pilates", section_mr: "पिलाटेस", type: "choice", condition: { id: "goals", includesAny: ["flexibility", "posture", "fit40", "pain"] }, q_en: "Have you tried Pilates before?", q_mr: "तुम्ही आधी पिलाटेस केले आहे का?", options: [{ id: "never", label_en: "Never tried", label_mr: "कधीही केले नाही", icon: "🆕" }, { id: "some", label_en: "A little bit", label_mr: "थोडे केले", icon: "🌱" }, { id: "regular", label_en: "I practice regularly", label_mr: "मी नियमित सराव करतो", icon: "🏆" }], required: false },
  { id: "pilates_format", section: 4, section_en: "Pilates", section_mr: "पिलाटेस", type: "choice", condition: { id: "goals", includesAny: ["flexibility", "posture", "fit40", "pain"] }, q_en: "Which Pilates format suits you?", q_mr: "तुम्हाला कोणता पिलाटेस फॉर्मॅट योग्य आहे?", options: [{ id: "group", label_en: "Group classes", label_mr: "ग्रुप वर्ग", icon: "👥" }, { id: "individual", label_en: "1-on-1 sessions", label_mr: "१-एक-१ सेशन्स", icon: "🙋" }, { id: "recorded", label_en: "Recorded, on my schedule", label_mr: "रेकॉर्डेड, माझ्या वेळापत्रकावर", icon: "📹" }, { id: "unsure", label_en: "Not sure yet", label_mr: "अजून माहीत नाही", icon: "🤔" }], required: false },
  // Section 5: Internal Health
  { id: "energy_level", section: 5, section_en: "Your Health", section_mr: "तुमचे आरोग्य", type: "choice", q_en: "How would you describe your energy levels?", q_mr: "तुमच्या ऊर्जा पातळीचे वर्णन कसे कराल?", options: [{ id: "low", label_en: "Often low or tired", label_mr: "अनेकदा कमी किंवा थकलेले", icon: "😴" }, { id: "moderate", label_en: "Moderate, varies", label_mr: "मध्यम, बदलत असते", icon: "😐" }, { id: "good", label_en: "Generally good", label_mr: "सामान्यतः चांगली", icon: "😊" }, { id: "high", label_en: "High, consistent", label_mr: "उच्च, सातत्यपूर्ण", icon: "🌟" }], required: true },
  // Section 6: Hormonal
  { id: "hormonal_interest", section: 6, section_en: "Hormonal Wellness", section_mr: "हार्मोनल वेलनेस", type: "choice", condition: { id: "goals", includesAny: ["hormonal", "energy", "muscle"] }, q_en: "Would you like to explore hormonal wellness?", q_mr: "तुम्ही हार्मोनल वेलनेस एक्सप्लोर करू इच्छिता का?", options: [{ id: "yes", label_en: "Yes, interested", label_mr: "होय, स्वारस्य आहे", icon: "✅" }, { id: "maybe", label_en: "Maybe, tell me more", label_mr: "कदाचित, अधिक सांगा", icon: "🤔" }, { id: "no", label_en: "Not right now", label_mr: "आत्ता नाही", icon: "➡️" }], required: false },
  // Section 7: Service preference
  { id: "service_mode", section: 7, section_en: "Getting Started", section_mr: "सुरुवात", type: "choice", q_en: "How do you prefer to work out?", q_mr: "तुम्हाला कसे व्यायाम करायला आवडते?", options: [{ id: "online", label_en: "Online (Zoom)", label_mr: "ऑनलाइन (झूम)", icon: "💻" }, { id: "studio", label_en: "Studio / in-person", label_mr: "स्टुडिओ / प्रत्यक्ष", icon: "🏢" }, { id: "combo", label_en: "Mix of both", label_mr: "दोन्हींचे मिश्रण", icon: "🔀" }], required: true },
  { id: "start_when", section: 7, section_en: "Getting Started", section_mr: "सुरुवात", type: "choice", q_en: "When are you looking to start?", q_mr: "तुम्ही कधी सुरू करू इच्छिता?", options: [{ id: "asap", label_en: "As soon as possible", label_mr: "शक्य तितक्या लवकर", icon: "🚀" }, { id: "2weeks", label_en: "Within 2 weeks", label_mr: "२ आठवड्यांत", icon: "📅" }, { id: "month", label_en: "This month", label_mr: "या महिन्यात", icon: "🗓️" }, { id: "exploring", label_en: "Just exploring", label_mr: "फक्त एक्सप्लोरिंग", icon: "🔍" }], required: true },
];

export const adminStats = {
  users: 1284,
  leads: 247,
  assessments: 891,
  conversions: 312,
  revenue: 847500,
  sessions: 48,
  programs: 8,
  whatsapp_leads: 183,
};

export const adminUsers = [
  { id: 1, name: "Meera Joshi", phone: "9876543210", email: "meera@example.com", age: 52, gender: "Female", lang: "EN", assessment: "Completed", program: "Group Pilates", subscription: "Active", payment: "₹2,999", last_activity: "2 hours ago" },
  { id: 2, name: "Suresh Patil", phone: "9823456789", email: "suresh@example.com", age: 47, gender: "Male", lang: "MR", assessment: "Completed", program: "Strength", subscription: "Active", payment: "₹3,499", last_activity: "1 day ago" },
  { id: 3, name: "Anita Kumar", phone: "9012345678", email: "anita@example.com", age: 55, gender: "Female", lang: "EN", assessment: "Pending", program: "—", subscription: "—", payment: "—", last_activity: "3 days ago" },
  { id: 4, name: "Prakash More", phone: "9345678901", email: "prakash@example.com", age: 61, gender: "Male", lang: "MR", assessment: "Completed", program: "Doctor + Nutrition", subscription: "Active", payment: "₹3,498", last_activity: "5 hours ago" },
  { id: 5, name: "Sunita Desai", phone: "9456789012", email: "sunita@example.com", age: 49, gender: "Female", lang: "EN", assessment: "Completed", program: "Individual Pilates", subscription: "Active", payment: "₹5,999", last_activity: "1 hour ago" },
];

export const whatsappTemplates = [
  { id: 1, name_en: "Welcome Message", name_mr: "स्वागत संदेश", status: "Active", lang: "Both", category: "Welcome", sent: 1284 },
  { id: 2, name_en: "Assessment Completed", name_mr: "मूल्यांकन पूर्ण", status: "Active", lang: "Both", category: "Assessment", sent: 891 },
  { id: 3, name_en: "Booking Confirmed", name_mr: "बुकिंग पुष्टी", status: "Active", lang: "Both", category: "Booking", sent: 312 },
  { id: 4, name_en: "Session Reminder", name_mr: "सेशन स्मरणपत्र", status: "Active", lang: "Both", category: "Reminder", sent: 748 },
  { id: 5, name_en: "Missed Session Follow-up", name_mr: "मिस सेशन पाठपुरावा", status: "Draft", lang: "EN only", category: "Follow-up", sent: 0 },
];

export const revenueData = [
  { month: "Mar", revenue: 48000, leads: 42, conversions: 18 },
  { month: "Apr", revenue: 67000, leads: 58, conversions: 24 },
  { month: "May", revenue: 89000, leads: 71, conversions: 31 },
  { month: "Jun", revenue: 124000, leads: 95, conversions: 47 },
  { month: "Jul", revenue: 156000, leads: 118, conversions: 58 },
  { month: "Aug", revenue: 198000, leads: 147, conversions: 73 },
];

export const funnelData = [
  { stage_en: "Ad Impression", stage_mr: "जाहिरात इम्प्रेशन", value: 12400 },
  { stage_en: "Lead", stage_mr: "लीड", value: 1284 },
  { stage_en: "Assessment", stage_mr: "मूल्यांकन", value: 891 },
  { stage_en: "Consultation", stage_mr: "सल्लामसलत", value: 498 },
  { stage_en: "Purchase", stage_mr: "खरेदी", value: 312 },
  { stage_en: "Active User", stage_mr: "सक्रिय वापरकर्ता", value: 287 },
];
